name: nma-data
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - pyarrow
  - requests
  - tqdm
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - ipykernel
  - pip
  - pytest
  - pip:
      - -e .
